<a href="https://colab.research.google.com/github/NadeemSB/IBM_FrontendExperience/blob/main/CoreML3_AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python -m pip install tensorflow==1.14
!python -m pip install keras==2.2.4
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Input, Convolution2D, MaxPooling2D, Dropout, Flatten, Dense
from keras.callbacks import Callback, ModelCheckpoint

In [ ]:
IMG_WIDTH, IMG_HEIGHT = 150, 150
TRAIN_DATA_DIR = '/content/drive/MyDrive/CoreML_AC/train'
VALIDATION_DATA_DIR = '/content/drive/MyDrive/CoreML_AC/valid'
NB_TRAIN_SAMPLES = 800
NB_VALIDATION_SAMPLES = 140
NB_EPOCH = 10
BATCH_SIZE = 32

In [ ]:
input = Input(shape=(IMG_WIDTH, IMG_HEIGHT,3))
x = Convolution2D(32, 3, 3)(input)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Convolution2D(64, 3, 3)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Convolution2D(128, 3, 3)(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Convolution2D(128, 3, 3, activation='relu')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)
x = Flatten()(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(2, activation='softmax')(x)
model = Model(inputs=input, outputs=x)

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        TRAIN_DATA_DIR,
        target_size=(IMG_WIDTH, IMG_HEIGHT),
        batch_size=BATCH_SIZE,
        class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
        VALIDATION_DATA_DIR,
        target_size=(IMG_WIDTH, IMG_HEIGHT),
        batch_size=BATCH_SIZE,
        class_mode='categorical')

model.fit_generator(
    train_generator,
    steps_per_epoch=NB_TRAIN_SAMPLES // 32,
    epochs=NB_EPOCH,
    validation_data=validation_generator,
    validation_steps=NB_VALIDATION_SAMPLES // 32)

model.save('model.h5')






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3))`
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3))`
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu")`
  


Found 85 images belonging to 2 classes.
Found 16 images belonging to 2 classes.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/10
25/25 [==============================] - 42s 2s/step - loss: 1.0129 - acc: 0.6313 - val_loss: 0.4547 - val_acc: 0.7500
Epoch 2/10
25/25 [==============================] - 37s 1s/step - loss: 0.5054 - acc: 0.7607 - val_loss: 0.4438 - val_acc: 0.8125
Epoch 3/10
25/25 [==============================] - 39s 2s/step - loss: 0.3929 - acc: 0.8416 - val_loss: 0.4302 - val_acc: 0.8125
Epoch 4/10
25/25 [==============================] - 37s 1s/step - loss: 0.3394 - acc: 0.8555 - val_loss: 0.4440 - val_acc: 0.8125
Epoch 5/10
25/25 [==============================] - 38s 2s/step - loss: 0.2010 - acc: 0.9234 - val_loss: 0.7088 - val_acc: 0.8125
Epoch 6/10
25/25 [==============================] - 37s 1s/step - loss: 0.2147 - acc: 0.9195 - val_loss: 0.7213 - val_acc: 0.6875
Epoch 7/10
25/25 [============================

In [ ]:
!pip uninstall h5py
!pip install h5py==2.10.0

Found existing installation: h5py 3.1.0
Uninstalling h5py-3.1.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/h5py-3.1.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libaec-9c9e97eb.so.0.0.10
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libhdf5-00e8fae8.so.200.0.0
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libhdf5_hl-383c339f.so.200.0.0
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libsz-e7aa62f5.so.2.0.1
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libz-eb09ad1d.so.1.2.3
    /usr/local/lib/python3.7/dist-packages/h5py/*
Proceed (y/n)? y
  Successfully uninstalled h5py-3.1.0
     |████████████████████████████████| 2.9 MB 28.1 MB/s 


In [ ]:
from keras.models import load_model
from keras.preprocessing import image
import numpy as np
from os import listdir
from os.path import isfile, join

# dimensions of our images
img_width, img_height = 150, 150

# load the model we saved
model = load_model('/content/model.h5')

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

mypath = "/content/drive/MyDrive/CoreML_AC/apredict"

onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
print(onlyfiles)
# predicting images
for file in onlyfiles:
    img = image.load_img("/content/drive/MyDrive/CoreML_AC/apredict/"+file, target_size=(img_width, img_height))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    
    result = model.predict(x)
    print("predict result..")
    print(result)

['2.jpg', '3.jpg', '4.jpg']
predict result..
[[1. 0.]]
predict result..
[[1. 0.]]
predict result..
[[1. 0.]]


# **COREML Conversion**

In [ ]:
!pip install coremltools==3.0b6

     |████████████████████████████████| 3.5 MB 16.6 MB/s 


In [ ]:
import coremltools
output_labels = ['Damaged', 'Undamaged']
coreml_model = coremltools.converters.keras.convert('model.h5', input_names=['image'], output_names=['output'],
                                                   class_labels=output_labels,
                                                   image_input_names='image')

coreml_model.author = 'IBM'
coreml_model.short_description = 'Dent Detection Classifier converted from a Keras model'
coreml_model.input_description['image'] = 'Takes as input an image'
coreml_model.output_description['output'] = 'Prediction as Damaged or Undamaged'
coreml_model.output_description['classLabel'] = 'Returns Damaged or Undamaged as class label'

0 : input_1, <keras.engine.input_layer.InputLayer object at 0x7fab15e8c650>
1 : conv2d_1, <keras.layers.convolutional.Conv2D object at 0x7fab15e8ca50>
2 : max_pooling2d_1, <keras.layers.pooling.MaxPooling2D object at 0x7fab15e8c890>
3 : conv2d_2, <keras.layers.convolutional.Conv2D object at 0x7fab15e8c9d0>
4 : max_pooling2d_2, <keras.layers.pooling.MaxPooling2D object at 0x7fab15e8cc90>
5 : conv2d_3, <keras.layers.convolutional.Conv2D object at 0x7fab15e8ce10>
6 : max_pooling2d_3, <keras.layers.pooling.MaxPooling2D object at 0x7fab15e8ce90>
7 : conv2d_4, <keras.layers.convolutional.Conv2D object at 0x7fab15e930d0>
8 : conv2d_4__activation__, <keras.layers.core.Activation object at 0x7fab15d0d950>
9 : max_pooling2d_4, <keras.layers.pooling.MaxPooling2D object at 0x7fab15e931d0>
10 : flatten_1, <keras.layers.core.Flatten object at 0x7fab15e933d0>
11 : dense_1, <keras.layers.core.Dense object at 0x7fab15e93410>
12 : dense_1__activation__, <keras.layers.core.Activation object at 0x7fab15d2

In [ ]:
coreml_model.save('DentDetection.mlmodel')

In [ ]:
coreml_model_path = "/content/DentDetection.mlmodel"
spec = coremltools.utils.load_spec(coreml_model_path)
builder = coremltools.models.neural_network.NeuralNetworkBuilder(spec=spec)
builder.inspect_layers(last=3)
builder.inspect_input_features()

[Id: 13], Name: dense_2__activation__ (Type: softmax)
          Updatable: False
          Input blobs: ['dense_2_output']
          Output blobs: ['output']
[Id: 12], Name: dense_2 (Type: innerProduct)
          Updatable: False
          Input blobs: ['dense_1__activation___output']
          Output blobs: ['dense_2_output']
[Id: 11], Name: dense_1__activation__ (Type: activation)
          Updatable: False
          Input blobs: ['dense_1_output']
          Output blobs: ['dense_1__activation___output']
[Id: 0] Name: image
          Type: imageType {
  width: 150
  height: 150
  colorSpace: RGB
}



In [ ]:
neuralnetwork_spec = builder.spec
neuralnetwork_spec.description.input[0].type.imageType.width = 150
neuralnetwork_spec.description.input[0].type.imageType.height = 150

"""from coremltools.proto import FeatureTypes_pb2 as _FeatureTypes_pb2
grayscale = _FeatureTypes_pb2.ImageFeatureType.ColorSpace.Value('GRAYSCALE')
neuralnetwork_spec.description.input[0].type.imageType.colorSpace = grayscale"""

# let's inspect the input again to confirm the change in input type
builder.inspect_input_features()

[Id: 0] Name: image
          Type: imageType {
  width: 150
  height: 150
  colorSpace: RGB
}



In [ ]:
model_spec = builder.spec
builder.make_updatable(['dense_1', 'dense_2'])

In [ ]:
builder.set_categorical_cross_entropy_loss(name='lossLayer', input= 'output')

from coremltools.models.neural_network import SgdParams
builder.set_sgd_optimizer(SgdParams(lr=0.01, batch=5))
builder.set_epochs(2)

Now adding input output_true as target for categorical cross-entropy loss layer.


In [ ]:
model_spec.isUpdatable = True
model_spec.specificationVersion = coremltools._MINIMUM_UPDATABLE_SPEC_VERSION

model_spec.description.trainingInput[0].shortDescription = 'Image for training and updating the model'
model_spec.description.trainingInput[1].shortDescription = 'Set the value as damaged or undamaged and update the model'

# Version History


*   V1 : 
*   V2 : 
*   V3 :
*   V4 : Exchanging the Output labels
*   V5 : Added images to dataset for application setup
*   V6 : Aircraft Dataset
*   V7 : Aircraft Dataset with new version images 46 and 47
*   V8 : Aircraft Dataset with refined new model

In [ ]:
coremltools.utils.save_spec(model_spec, 'DentDetectionUpdatable(V_8).mlmodel')

In [ ]:
builder.inspect_loss_layers()

[Id: 0], Name: lossLayer (Type: categoricalCrossEntropyLossLayer)
          Loss Input: output
          Loss Target: output_true
